<script lang="ts">
  import { Input } from "$lib/components/ui/input";
  import { Textarea } from "$lib/components/ui/textarea/index.js";
  import { Label } from "$lib/components/ui/label";
  import * as Select from "$lib/components/ui/select/index.js";
  import { Button } from "$lib/components/ui/button";
  import { Checkbox } from "$lib/components/ui/checkbox";
  import { IconAlertCircle } from "@tabler/icons-svelte";
  import { Alert, AlertDescription } from "$lib/components/ui/alert";

  interface PackBasicsData {
    name: string;
    slug: string;
    description: string;
    image_url: string;
    game: "mtg" | "pokemon";
    rip_cost: number;
    is_active: boolean;
    cards_per_pack: number;
  }

  let {
    data,
    onComplete,
  }: {
    data: PackBasicsData;
    onComplete: (data: PackBasicsData) => void;
  } = $props();

  let formData = $state({ ...data });
  let slugManuallyEdited = $state(false);
  let lastAutoGeneratedSlug = $state(data.slug || "");

  function generateSlug(name: string): string {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_-]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }

  function handleNameBlur() {
    // Only auto-generate slug if it hasn't been manually edited
    if (!slugManuallyEdited) {
      const autoGeneratedSlug = generateSlug(formData.name);
      if (autoGeneratedSlug) {
        formData.slug = autoGeneratedSlug;
        lastAutoGeneratedSlug = autoGeneratedSlug;
      }
    }
  }

  function handleSlugChange() {
    // Mark slug as manually edited if it differs from the last auto-generated value
    if (formData.slug !== lastAutoGeneratedSlug) {
      slugManuallyEdited = true;
    }
  }

  // Derived errors - computed reactively without side effects
  const errors = $derived.by(() => {
    const errs: Record<string, string> = {};

    if (!formData.name.trim()) {
      errs.name = "Pack name is required";
    }

    if (!formData.slug.trim()) {
      errs.slug = "Slug is required";
    } else if (!/^[a-z0-9-]+$/.test(formData.slug)) {
      errs.slug = "Slug can only contain lowercase letters, numbers, and hyphens";
    }

    if (formData.rip_cost <= 0 || !Number.isInteger(formData.rip_cost)) {
      errs.rip_cost = "Rip cost must be a positive integer";
    }

    if (!formData.game) {
      errs.game = "Game selection is required";
    }

    return errs;
  });

  const isValid = $derived(Object.keys(errors).length === 0);

  function handleSubmit() {
    if (isValid) {
      onComplete(formData);
    }
  }
</script>

<div class="space-y-6 max-w-2xl mx-auto">
  <div>
    <h2 class="text-xl font-semibold mb-1">Pack Basics</h2>
    <p class="text-sm text-muted-foreground">
      Define the pack identity, pricing, and basic information.
    </p>
  </div>

  <div class="space-y-4">
    <div class="space-y-2">
      <Label for="name">Pack Name *</Label>
      <Input
        id="name"
        bind:value={formData.name}
        onblur={handleNameBlur}
        placeholder="e.g., Standard Pack"
        class={errors.name ? "border-destructive" : ""}
      />
      {#if errors.name}
        <p class="text-sm text-destructive">{errors.name}</p>
      {/if}
    </div>

    <div class="space-y-2">
      <Label for="slug">Slug *</Label>
      <Input
        id="slug"
        bind:value={formData.slug}
        oninput={handleSlugChange}
        placeholder="e.g., standard-pack"
        class={errors.slug ? "border-destructive" : ""}
      />
      {#if errors.slug}
        <p class="text-sm text-destructive">{errors.slug}</p>
      {/if}
      <p class="text-xs text-muted-foreground">
        URL-friendly identifier (auto-generated from name on blur, editable)
      </p>
    </div>

    <div class="space-y-2">
      <Label for="description">Description</Label>
      <Textarea
        id="description"
        bind:value={formData.description}
        rows={4}
        placeholder="Describe what makes this pack special..."
      />
    </div>

    <div class="space-y-2">
      <Label for="image_url">Pack Image URL</Label>
      <Input
        id="image_url"
        bind:value={formData.image_url}
        type="url"
        placeholder="https://example.com/pack-image.jpg"
      />
      <p class="text-xs text-muted-foreground">
        URL to the pack image (or leave empty for now)
      </p>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div class="space-y-2">
        <Label for="game">Game *</Label>
        <Select.Root type="single" bind:value={formData.game}>
          <Select.Trigger id="game" class={errors.game ? "border-destructive" : ""}>
            {#if formData.game === "mtg"}
              Magic: The Gathering
            {:else if formData.game === "pokemon"}
              Pokémon
            {:else}
              Select game
            {/if}
          </Select.Trigger>
          <Select.Content>
            <Select.Item value="mtg">Magic: The Gathering</Select.Item>
            <Select.Item value="pokemon">Pokémon</Select.Item>
          </Select.Content>
        </Select.Root>
        {#if errors.game}
          <p class="text-sm text-destructive">{errors.game}</p>
        {/if}
      </div>

      <div class="space-y-2">
        <Label for="rip_cost">Rip Cost *</Label>
        <Input
          id="rip_cost"
          type="number"
          min="1"
          step="1"
          bind:value={formData.rip_cost}
          class={errors.rip_cost ? "border-destructive" : ""}
        />
        {#if errors.rip_cost}
          <p class="text-sm text-destructive">{errors.rip_cost}</p>
        {/if}
      </div>
    </div>

    <div class="space-y-2">
      <Label for="cards_per_pack">Cards per Pack</Label>
      <Input
        id="cards_per_pack"
        type="number"
        min="1"
        step="1"
        bind:value={formData.cards_per_pack}
        readonly
      />
      <p class="text-xs text-muted-foreground">
        Default: 1 card per pack (read-only for MVP)
      </p>
    </div>

    <div class="flex items-center space-x-2">
      <Checkbox
        id="is_active"
        bind:checked={formData.is_active}
      />
      <Label for="is_active" class="font-normal cursor-pointer">
        Activate pack immediately after creation
      </Label>
    </div>
  </div>

  {#if !isValid}
    <Alert variant="destructive">
      <IconAlertCircle size={16} />
      <AlertDescription>
        Please fix the errors above before continuing.
      </AlertDescription>
    </Alert>
  {/if}

  <div class="flex justify-end pt-4">
    <Button onclick={handleSubmit} disabled={!isValid}>
      Save & Continue
    </Button>
  </div>
</div>

