<script lang="ts">
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import * as Select from "$lib/components/ui/select/index.js";
  import { Button } from "$lib/components/ui/button";
  import { superForm } from "sveltekit-superforms";
  import { zodClient } from "sveltekit-superforms/adapters";
  import { z } from "zod";

  interface Game {
    id: string;
    name: string;
    code: string;
  }

  let {
    open = $bindable(false),
    games = [],
    onComplete,
  } = $props<{
    open?: boolean;
    games?: Game[];
    onComplete?: (packId: string) => void;
  }>();

  let isLoading = $state(false);

  const packSchema = z.object({
    name: z.string().min(3, "Pack name must be at least 3 characters"),
    slug: z.string().min(1, "Slug is required").regex(/^[a-z0-9-]+$/, "Slug can only contain lowercase letters, numbers, and hyphens"),
    game_code: z.string().min(1, "Game is required"),
  });

  const form = superForm(
    {
      name: "",
      slug: "",
      game_code: "",
    },
    {
      SPA: true,
      validators: zodClient(packSchema as any),
      onSubmit: () => {
        isLoading = true;
      },
      onResult: async ({ result }) => {
        isLoading = false;

        if (result.type === "success" && "data" in result && result.data?.success && result.data?.packId) {
          // Close modal first
          open = false;

          // Then navigate
          if (onComplete) {
            onComplete(result.data.packId);
          }
        } else if (result.type === "failure" && "data" in result) {
          const errorMessage = (result.data as { error?: string })?.error || "Unknown error";
          console.error("Error creating pack:", errorMessage);
        }
      },
    }
  );

  const { form: formData, errors, enhance } = form;

  let slugManuallyEdited = $state(false);
  let lastAutoGeneratedSlug = $state("");

  function generateSlug(name: string): string {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_-]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }

  function handleNameBlur() {
    if (!slugManuallyEdited) {
      const autoGeneratedSlug = generateSlug($formData.name);
      if (autoGeneratedSlug) {
        $formData.slug = autoGeneratedSlug;
        lastAutoGeneratedSlug = autoGeneratedSlug;
      }
    }
  }

  function handleSlugChange() {
    if ($formData.slug !== lastAutoGeneratedSlug) {
      slugManuallyEdited = true;
    }
  }
</script>

<Dialog.Root bind:open>
  <Dialog.Content class="max-w-lg">
    <Dialog.Header>
      <Dialog.Title>Create New Pack</Dialog.Title>
      <Dialog.Description>
        Start by defining the basic fields. You'll configure tiers, cards, and pricing in the editor.
      </Dialog.Description>
    </Dialog.Header>

    <form method="POST" action="?/create" use:enhance class="space-y-4">
      <div class="space-y-2">
        <Label for="name">Pack Name *</Label>
        <Input
          id="name"
          name="name"
          bind:value={$formData.name}
          onblur={handleNameBlur}
          placeholder="e.g., Standard Pack"
          class={$errors.name ? "border-destructive" : ""}
        />
        {#if $errors.name}
          <p class="text-sm text-destructive">{$errors.name}</p>
        {/if}
      </div>

      <div class="space-y-2">
        <Label for="slug">Slug *</Label>
        <Input
          id="slug"
          name="slug"
          bind:value={$formData.slug}
          oninput={handleSlugChange}
          placeholder="e.g., standard-pack"
          class={$errors.slug ? "border-destructive" : ""}
        />
        <p class="text-xs text-muted-foreground">
          URL-friendly identifier (auto-generated from name, editable)
        </p>
        {#if $errors.slug}
          <p class="text-sm text-destructive">{$errors.slug}</p>
        {/if}
      </div>

      <div class="space-y-2">
        <Label for="game_code">Game *</Label>
        {#if games.length > 0}
          <Select.Root type="single" name="game_code" bind:value={$formData.game_code}>
            <Select.Trigger id="game_code" class={$errors.game_code ? "border-destructive" : ""}>
              {#if $formData.game_code}
                {games.find((g: Game) => g.code === $formData.game_code)?.name || "Select game"}
              {:else}
                Select game
              {/if}
            </Select.Trigger>
            <Select.Content>
              {#each games as game (game.id)}
                <Select.Item value={game.code}>{game.name}</Select.Item>
              {/each}
            </Select.Content>
          </Select.Root>
        {:else}
          <div class="border rounded-md px-3 py-2 text-sm text-muted-foreground">
            Loading games...
          </div>
        {/if}
        {#if $errors.game_code}
          <p class="text-sm text-destructive">{$errors.game_code}</p>
        {/if}
      </div>

      <Dialog.Footer>
        <Button type="button" variant="outline" onclick={() => (open = false)}>
          Cancel
        </Button>
        <Button type="submit" disabled={isLoading}>
          {isLoading ? "Creating..." : "Create Pack"}
        </Button>
      </Dialog.Footer>
    </form>
  </Dialog.Content>
</Dialog.Root>
